version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
# TODO: this is for using binding.break - need to check if this is ok in prod
# from https://medium.com/gogox-technology/debugging-rails-app-with-docker-compose-39a3767962f4
    stdin_open: true
    tty: true

volumes:
  bundle:
