# To edit credentials
# 1) get master.key file from someone
# 2) put in config/master.key
# 3) run dcred (should be ~/.zschrc)
# dred =
#   docker run --rm -it --mount type=bind,src=${PWD},target=/usr/src/app \
#   zeemee-ui_web /bin/sh -c \
#   'apt update && apt install -y vim && EDITOR=vim bin/rails credentials:edit'
<%
  def config(field)
    Rails.application.credentials.dig(Rails.env.to_sym, field)
  end
%>
development:
  adapter: <%= config(:db_adapter) %>
  encoding: <%= config(:db_encoding) %>
  database: <%= config(:db_database) %>
  username: <%= config(:db_username) %>
  password: <%= config(:db_password) %>
  host: <%= config(:db_host) %>
  port: <%= config(:db_port) %>
  pool: <%= config(:db_pool) %>
