default: &default
  adapter: postgresql
  encoding: unicode
  # host: db
  # username: postgres
  # password:
  pool: <%= ENV['MAX_THREADS'] || 5 %>

development:
  adapter: postgresql
  encoding: unicode
  database: zeemee_staging
  username: zeemee_admin
  password: FUA3p654h9D79Sb
  host: stage-rails.cly0cxysh0so.us-east-1.rds.amazonaws.com
  port: 5432
